## Postgres
spring.application.name=module-306-backend
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/trackify

## S3 MinIO
s3.url=localhost:9000
s3.username=minioadmin
s3.password=minioadmin

## Keycloak
spring.security.oauth2.client.provider.trackify.issuer-uri=http://localhost:8081/realms/trackify

spring.security.oauth2.client.registration.trackify.provider=trackify
spring.security.oauth2.client.registration.trackify.client-name=trackify
spring.security.oauth2.client.registration.trackify.client-id=trackify
spring.security.oauth2.client.registration.trackify.client-secret=OW0m4TMAdVvMBFvtHxTze9gvYpj39w3P
spring.security.oauth2.client.registration.trackify.scope=openid,offline_access,profile
spring.security.oauth2.client.registration.trackify.authorization-grant-type=authorization_code